config/routes.rb
Rails.application.routes.draw do
  root 'chat_rooms#index'
  devise_for :users

  resources :chat_rooms, only: [:index, :new, :create, :show]

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy

  validates :user, :title, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room

  validates :user, :chat_room, presence: true
  validates :body, presence: true, length: {minimum: 2, maximum: 1000}

  after_create_commit { MessageBroadcastJob.perform_later(self) }

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy


  def name
    email.split('@').first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  def index
    @chat_rooms = ChatRoom.all
  end

  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      flash[:success] = 'Chat room added!'
      redirect_to chat_rooms_path
    else
      render 'new'
    end
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:title)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, opts = {})
    opts[:alt] = user.name
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
              opts
  end
end

app/helpers/bootstrap_flash_helper.rb
module BootstrapFlashHelper
  ALERT_TYPES = [:success, :info, :warning, :danger] unless const_defined?(:ALERT_TYPES)

  def bootstrap_flash(options = {})
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?

      type = type.to_sym
      type = :success if type == :notice
      type = :danger  if type == :alert
      type = :danger  if type == :error
      next unless ALERT_TYPES.include?(type)

      tag_class = options.extract!(:class)[:class]
      tag_options = {
          class: "alert fade in alert-#{type} #{tag_class} col-xs-12 col-sm-8 col-sm-offset-2"
      }.merge(options)

      close_button = content_tag(:button, raw('&times;'), type: 'button', class: 'close', 'data-dismiss' => 'alert')

      Array(message).each do |msg|
        text = content_tag(:div, close_button + msg, tag_options)
        flash_messages << text if msg
      end
    end
    flash_messages.join('\n').html_safe
  end
end

app/views/chat_rooms/_chat_room.html.haml
%li
  = link_to "Enter #{chat_room.title}", chat_room_path(chat_room)

app/views/chat_rooms/index.html.haml
.page-header
  %h1 Chat rooms
  = link_to 'New chat room', new_chat_room_path, class: 'btn btn-primary'
.row
  .col-sm-12
    %ul
      = render @chat_rooms

app/views/chat_rooms/new.html.haml
.page-header
  %h1 Add chat room

.col-sm-8
  = form_for @chat_room, html: {class: 'form'} do |f|
    .form-group
      = f.label :title
      = f.text_field :title, autofocus: true, class: 'form-control'
    .form-group
      = f.submit 'Add!', class: 'btn btn-primary'

app/views/chat_rooms/show.html.haml
.page-header
  %h1
    = @chat_room.title
.row
  .col-sm-12
    #messages{ 'data-chat-room-id': @chat_room.id }
      = render @chat_room.messages
.row
  .col-sm-8
    = form_for Message.new, url: '#', html: { class: 'form' } do |f|
      .form-group
        = f.label :body
        = f.text_area :body, class: 'form-control', rows: 5
        %small.text-muted From 2 to 1000 characters
      .form-group
        = f.submit 'Post message', class: 'btn btn-primary btn-lg'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type'}/
    %title CableChat
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    .container
      .row
        = bootstrap_flash
      .row
        = yield

app/views/messages/_message.html.haml
.card
  .card-block
    .row
      .col-sm-1
        = gravatar_for message.user
      .col-sm-11
        %p.card-text
          %span.text-muted
            = message.user.name
            at
            = message.timestamp
          %br
          = message.body
%hr